#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math, hashlib

class Receiver:
    def __init__(self):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)
        self.exp_seq = 0
        self.buffer = {}

        self.remote_host = None
        self.remote_port = None

    def checksum(self, msg):
        # hash the packet contents so we can detect corruption
        return hashlib.md5(json.dumps(msg, sort_keys=True).encode("utf-8")).hexdigest()

    def send(self, message):
        # attach checksum before sending so sender can verify integrity
        message["checksum"] = self.checksum(message)
        self.log("Sent ACK seq=%s" % message.get("seq"))
        self.socket.sendto(json.dumps(message).encode("utf-8"), (self.remote_host, self.remote_port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        # Grab the remote host/port if we don't already have it
        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        # Make sure we're talking to the same remote host
        if addr != (self.remote_host, self.remote_port):
            self.log("Error:  Received response from unexpected remote; ignoring")
            return None
        else:
            self.log("Received message (%d bytes)" % len(data))
            # try to parse the JSON, drop corrupted packets
            try:
                msg = json.loads(data.decode("utf-8"))
            except (json.JSONDecodeError, UnicodeDecodeError):
                self.log("Error:  Received corrupted packet; dropping")
                return None

            # verify checksum to make sure packet wasnt mangled in transit
            if "checksum" not in msg:
                self.log("Error:  Received packet without checksum; dropping")
                return None
            received_checksum = msg.pop("checksum")
            if received_checksum != self.checksum(msg):
                self.log("Error:  Checksum mismatch on received packet; dropping")
                return None

            return msg

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def run(self):
        while True:
            socks = select.select([self.socket], [], [])[0]
            for conn in socks:
                msg = self.recv(conn)

                if msg:
                    # make sure the packet has the fields we need, drop if not
                    if "seq" not in msg or "data" not in msg:
                        self.log("Error:  Received malformed packet; dropping")
                        continue

                    seq = msg["seq"]
                    data = msg["data"]
                    ack_seq = self.exp_seq - 1

                    if seq == self.exp_seq:
                        # Print out the data to stdout
                        print(data, end='', flush=True)
                        # In-order packet
                        self.exp_seq += 1

                        # print out buffered packets now that they are in order
                        while self.exp_seq in self.buffer:
                            buff_data = self.buffer.pop(self.exp_seq)
                            print(buff_data, end='', flush=True)
                            self.exp_seq += 1

                        # Send back an ack for highest seq we have seen so far
                        ack_seq = self.exp_seq - 1
                    elif seq > self.exp_seq:
                        # Out of order packet
                        self.log("Error:  Received packet with sequence number %d, expected %d, therefore I am missing a packet" % (seq, self.exp_seq))
                        if seq not in self.buffer:
                            self.buffer[seq] = data
                    elif seq < self.exp_seq:
                        # Duplicate packet
                        self.log("Error:  Received packet with sequence number %d, expected %d, therefore I have received a duplicate packet" % (seq, self.exp_seq))

                    # only send an ack if we have received at least one in-order packet
                    if ack_seq >= 0:
                        self.send({ "type": "ack", "seq": ack_seq })

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    sender = Receiver()
    sender.run()
