#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math, zlib

DATA_SIZE = 1400

class Sender:
    def __init__(self, host, port):
        self.host = host
        self.port = int(port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.lowest_unacked = 0
        self.seq = 0
        self.unacked = {}
        self.eof = False
        self.last_ack = None
        self.dup_ack_count = 0

        # congestion window and slow start threshold
        self.cwnd = 1
        self.ssthresh = 64
        self.in_fast_recovery = False

        # RTT estimation for dynamic timeout
        self.srtt = None
        self.rto = 1.5

        self.remote_host = None
        self.remote_port = None

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def checksum(self, msg):
        return format(zlib.crc32(json.dumps(msg, sort_keys=True, separators=(",", ":")).encode()) & 0xffffffff, "08x")

    def send(self, message):
        message["checksum"] = self.checksum(message)
        self.socket.sendto(json.dumps(message, separators=(",", ":")).encode(), (self.host, self.port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        if addr != (self.remote_host, self.remote_port):
            return None
        else:
            try:
                msg = json.loads(data.decode())
            except (json.JSONDecodeError, UnicodeDecodeError):
                return None

            if "checksum" not in msg:
                return None
            received_checksum = msg.pop("checksum")
            if received_checksum != self.checksum(msg):
                return None

            return msg

    def update_rtt(self, send_time):
        sample = time.time() - send_time
        if self.srtt is None:
            self.srtt = sample
        else:
            self.srtt = 0.875 * self.srtt + 0.125 * sample
        self.rto = max(1.0, 2 * self.srtt)

    def run(self):
        while True:
            sockets = [self.socket, sys.stdin] if not self.eof and self.seq < self.lowest_unacked + int(self.cwnd) else [self.socket]

            # set select timeout based on when the oldest unacked packet will expire
            timeout = 0.02
            if self.unacked and self.lowest_unacked in self.unacked:
                _, send_time, _ = self.unacked[self.lowest_unacked]
                timeout = min(timeout, max(0, self.rto - (time.time() - send_time)))

            socks = select.select(sockets, [], [], timeout)[0]
            for conn in socks:
                if conn == self.socket:
                    data = self.recv(conn)

                    if data:
                        if "seq" not in data:
                            continue
                        ack_seq = int(data["seq"])

                        # ignore stale ACKs behind our window
                        if ack_seq < self.lowest_unacked - 1:
                            continue

                        # dupe ACK handling
                        if ack_seq == self.lowest_unacked - 1:
                            if self.last_ack == ack_seq:
                                self.dup_ack_count += 1
                            else:
                                self.last_ack = ack_seq
                                self.dup_ack_count = 1

                            # fast retransmit on 3 dupe ACKs
                            if self.dup_ack_count == 3 and not self.in_fast_recovery and len(self.unacked) >= 4:
                                self.ssthresh = max(int(self.cwnd / 2), 1)
                                self.cwnd = self.ssthresh + 3
                                self.in_fast_recovery = True
                                if self.lowest_unacked in self.unacked:
                                    pkt_data, _, _ = self.unacked[self.lowest_unacked]
                                    msg = { "type": "msg", "data": pkt_data, "seq": self.lowest_unacked }
                                    self.send(msg)
                                    self.unacked[self.lowest_unacked] = (pkt_data, time.time(), True)
                            elif self.dup_ack_count > 3 and self.in_fast_recovery:
                                self.cwnd += 1
                            continue

                        # new ACK advances the window
                        self.last_ack = ack_seq
                        self.dup_ack_count = 0

                        # RTT sampling (skip retransmitted per Karn's algorithm)
                        if ack_seq in self.unacked:
                            _, send_time, retransmitted = self.unacked[ack_seq]
                            if not retransmitted:
                                self.update_rtt(send_time)

                        # clear everything up to ack_seq
                        while self.lowest_unacked <= ack_seq:
                            self.unacked.pop(self.lowest_unacked, None)
                            self.lowest_unacked += 1

                        if self.in_fast_recovery:
                            self.cwnd = self.ssthresh
                            self.in_fast_recovery = False
                        else:
                            if self.cwnd < self.ssthresh:
                                self.cwnd += 1
                            else:
                                self.cwnd += 1.0 / self.cwnd

                elif conn == sys.stdin:
                    data = sys.stdin.read(DATA_SIZE)
                    if len(data) == 0:
                        self.eof = True
                        continue

                    msg = { "type": "msg", "data": data, "seq": self.seq }
                    self.unacked[self.seq] = (data, time.time(), False)
                    self.send(msg)
                    self.seq += 1

            # timeout retransmission
            if self.unacked:
                now = time.time()
                if self.lowest_unacked in self.unacked:
                    _, send_time, _ = self.unacked[self.lowest_unacked]
                    if now - send_time >= self.rto:
                        self.ssthresh = max(int(self.cwnd / 2), 1)
                        self.cwnd = 1
                        self.in_fast_recovery = False
                        self.last_ack = None
                        self.dup_ack_count = 0
                        # retransmit first few unacked packets
                        for s in sorted(self.unacked.keys())[:3]:
                            pkt_data, _, _ = self.unacked[s]
                            msg = { "type": "msg", "data": pkt_data, "seq": s }
                            self.send(msg)
                            self.unacked[s] = (pkt_data, now, True)
            if self.eof and not self.unacked:
                self.log("All done!")
                sys.exit(0)
        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()
