#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math, zlib

class Receiver:
    def __init__(self):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)
        self.exp_seq = 0
        self.buffer = {}

        self.remote_host = None
        self.remote_port = None

    def checksum(self, msg):
        return format(zlib.crc32(json.dumps(msg, sort_keys=True, separators=(",", ":")).encode()) & 0xffffffff, "08x")

    def send(self, message):
        message["checksum"] = self.checksum(message)
        self.socket.sendto(json.dumps(message, separators=(",", ":")).encode(), (self.remote_host, self.remote_port))

    def recv(self, socket):
        data, addr = socket.recvfrom(65535)

        if self.remote_host is None:
            self.remote_host = addr[0]
            self.remote_port = addr[1]

        if addr != (self.remote_host, self.remote_port):
            return None
        else:
            try:
                msg = json.loads(data.decode())
            except (json.JSONDecodeError, UnicodeDecodeError):
                return None

            if "checksum" not in msg:
                return None
            received_checksum = msg.pop("checksum")
            if received_checksum != self.checksum(msg):
                return None

            return msg

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()

    def run(self):
        while True:
            socks = select.select([self.socket], [], [])[0]
            for conn in socks:
                msg = self.recv(conn)

                if msg:
                    if "seq" not in msg or "data" not in msg:
                        continue

                    seq = msg["seq"]
                    data = msg["data"]
                    ack_seq = self.exp_seq - 1

                    if seq == self.exp_seq:
                        # in-order packet, flush it and any buffered ones after it
                        chunks = [data]
                        self.exp_seq += 1

                        while self.exp_seq in self.buffer:
                            chunks.append(self.buffer.pop(self.exp_seq))
                            self.exp_seq += 1

                        sys.stdout.write("".join(chunks))
                        sys.stdout.flush()

                        ack_seq = self.exp_seq - 1
                    elif seq > self.exp_seq:
                        # out of order, buffer it
                        if seq not in self.buffer:
                            self.buffer[seq] = data
                    # else: duplicate, just re-ack

                    if ack_seq >= 0:
                        self.send({ "type": "ack", "seq": ack_seq })

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    sender = Receiver()
    sender.run()
